//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiposInvWM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devoluciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devoluciones()
        {
            this.ImagenesDevolucion = new HashSet<ImagenesDevolucion>();
            this.ListaPerifericosDevo = new HashSet<ListaPerifericosDevo>();
        }
    
        public int devo_id { get; set; }
        public string equi_cod { get; set; }
        public int ficha_id { get; set; }
        public Nullable<System.DateTime> devo_fecha { get; set; }
    
        public virtual FichaComputo FichaComputo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenesDevolucion> ImagenesDevolucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaPerifericosDevo> ListaPerifericosDevo { get; set; }
    }
}
