//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiposInvWM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int emp_id { get; set; }
        public string emp_pnom { get; set; }
        public string emp_pape { get; set; }
        public string emp_compania { get; set; }
        public string emp_correo { get; set; }
        public string emp_numemp { get; set; }
    }
}
