//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiposInvWM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipos()
        {
            this.FichaComputo = new HashSet<FichaComputo>();
            this.Reparaciones = new HashSet<Reparaciones>();
        }
    
        public int equi_id { get; set; }
        public string equi_prefijo { get; set; }
        public int equi_cod { get; set; }
        public string equi_marca { get; set; }
        public string equi_tipo { get; set; }
        public string equi_proveedor { get; set; }
        public Nullable<bool> equi_garantia { get; set; }
        public string equi_serie { get; set; }
        public Nullable<int> equi_disco { get; set; }
        public string equi_procesador { get; set; }
        public Nullable<int> equi_ram { get; set; }
        public Nullable<decimal> equi_ghz { get; set; }
        public string equi_modelo { get; set; }
        public string equi_status { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<bool> equi_politica { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FichaComputo> FichaComputo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reparaciones> Reparaciones { get; set; }
    }
}
