//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiposInvWM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipos()
        {
            this.FichaComputo = new HashSet<FichaComputo>();
            this.Reparacion = new HashSet<Reparacion>();
        }
    
        public int equi_id { get; set; }
        public string equi_prefijo { get; set; }
        public string equi_cod { get; set; }
        public string equi_marca { get; set; }
        public string equi_tipo { get; set; }
        public string equi_proveedor { get; set; }
        public string equi_serie { get; set; }
        public string equi_disco { get; set; }
        public string equi_procesador { get; set; }
        public string equi_ram { get; set; }
        public Nullable<decimal> equi_ghz { get; set; }
        public string equi_modelo { get; set; }
        public string equi_status { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<bool> equi_politica { get; set; }
        public string equi_ordencompra { get; set; }
        public Nullable<decimal> equi_precio { get; set; }
        public string equi_empresa { get; set; }
        public string equi_proyecto { get; set; }
        public string equi_dpto { get; set; }
        public string equi_observacion { get; set; }
        public Nullable<System.DateTime> equi_garantia { get; set; }
        public string emp_nom { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FichaComputo> FichaComputo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reparacion> Reparacion { get; set; }
    }
}
