//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiposInvWM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaPerifericos
    {
        public int lisper_id { get; set; }
        public Nullable<int> per_id { get; set; }
        public string per_nom { get; set; }
        public string per_tipo { get; set; }
        public string per_cod { get; set; }
        public Nullable<int> ficha_id { get; set; }
        public string per_marca { get; set; }
        public string per_estado { get; set; }
        public string per_serie { get; set; }
    
        public virtual FichaComputo FichaComputo { get; set; }
        public virtual Perifericos Perifericos { get; set; }
    }
}
