//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiposInvWM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaPerifericos
    {
        public int lisper_id { get; set; }
        public Nullable<int> per_id { get; set; }
        public string per_nom { get; set; }
        public string per_tipo { get; set; }
        public string per_cod { get; set; }
        public Nullable<int> ficha_id { get; set; }
    
        public virtual FichaComputo FichaComputo { get; set; }
        public virtual Perifericos Perifericos { get; set; }
    }
}
