//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiposInvWM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perifericos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Perifericos()
        {
            this.ListaPerifericos = new HashSet<ListaPerifericos>();
        }
    
        public int per_id { get; set; }
        public string per_prefijo { get; set; }
        public int per_cod { get; set; }
        public string per_tipo { get; set; }
        public string per_marca { get; set; }
        public string per_estado { get; set; }
        public string per_serie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaPerifericos> ListaPerifericos { get; set; }
    }
}
