//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiposInvWM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periferico
    {
        public string per_id { get; set; }
        public string per_tipo { get; set; }
        public string per_marca { get; set; }
        public string per_estado { get; set; }
        public string per_serie { get; set; }
    }
}
