//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiposInvWM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reparaciones
    {
        public int repa_id { get; set; }
        public Nullable<int> equi_id { get; set; }
        public string repa_tipo { get; set; }
        public string repa_detalle { get; set; }
        public Nullable<System.DateTime> repa_fecha { get; set; }
    
        public virtual Equipos Equipos { get; set; }
    }
}
