//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiposInvWM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reparaciones
    {
        public int repa_id { get; set; }
        public Nullable<int> equi_id { get; set; }
        public string repa_tipo { get; set; }
        public string repa_detalle { get; set; }
        public Nullable<System.DateTime> repa_fecha { get; set; }
    
        public virtual Equipos Equipos { get; set; }
    }
}
