//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiposInvWM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareInstalado
    {
        public int softinstal_id { get; set; }
        public string softinstal_nom { get; set; }
        public Nullable<bool> softinstal_instalado { get; set; }
        public Nullable<int> ficha_id { get; set; }
    
        public virtual FichaComputo FichaComputo { get; set; }
    }
}
