//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiposInvWM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int user_id { get; set; }
        public string user_nom { get; set; }
        public string user_ape { get; set; }
        public string user_correo { get; set; }
        public string user_contrasenia { get; set; }
        public bool user_escritura { get; set; }
        public bool user_lectura { get; set; }
    }
}
