//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquiposInvWM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int user_id { get; set; }
        public string user_nom { get; set; }
        public string user_ape { get; set; }
        public string user_correo { get; set; }
        public string user_contrasenia { get; set; }
        public bool user_escritura { get; set; }
        public bool user_lectura { get; set; }
    }
}
